return {
	{"arena", "Arena"},
	{"befallen", "Befallen"},
	{"blackburrow", "Blackburrow"},
	{"cazicthule", "Cazic Thule"},
	{"commons", "Commonlands"},
	{"crushbone", "Crushbone"},
	{"dulak", "Dulak Harbor"},
	{"erudnext", "Erudin"},
	{"gukbottom", "Guk - Lower"},
	{"guktop", "Guk - Upper"},
	{"gunthak", "Gunthak"},
	{"highkeep", "Highkeep"},
	{"hole", "Hole"},
	{"jaggedpine", "Jaggedpine"},
	{"lavastorm", "Lavastorm"},
	{"mistmoore", "Mistmoore"},
	{"nadox", "Crypt of Nadox"},
	{"najena", "Najena"},
	{"northkarana", "North Karana"},
	{"nro", "North Ro"},
	{"oot", "Ocean of Tears"},
	{"paw", "Splitpaw"},
	{"permafrost", "Permafrost"},
	{"qeytoqrg", "Qeynos Hills"},
	{"qrg", "Qeynos"},
	{"runnyeye", "Runnyeye"},
	{"soldunga", "Solusek's Eye (Solusek A)"},
	{"soldungb", "Nagafen's Lair (Solusek B)"},
	{"soldungc", "Caverns of Exile (Solusek C)"},
	{"sro", "South Ro"},
	{"steamfont", "Steamfont"},
	{"stonebrunt", "Stonebrunt"},
	{"unrest", "Unrest"},
	{"warrens", "Warrens"}
}