return {
	{"burningwood", "Burning Woods"},
	{"charasis", "Charasis (Howling Stones)"},
	{"chardok", "Chardok"},
	{"citymist", "City of Mist"},
	{"dalnir", "Crypt of Dalnir"},
	{"dreadlands", "Dreadlands"},
	{"emeraldjungle", "Emerald Jungle"},
	{"fieldofbone", "Field of Bone"},
	{"kaesora", "Kaesora"},
	{"karnor", "Karnor's Castle"},
	{"kurn", "Kurn's Tower"},
	{"lakeofillomen", "Lake of Ill Omen"},
	{"nurga", "Mines of Nurga"},
	{"sebilis", "Sebilis"},
	{"skyfire", "Skyfire Mountains"},
	{"timorous", "Timorous Deep"},
	{"trakanon", "Trakanon"},
	{"veksar", "Veksar"},
	{"warslikswood", "Warsliks Woods"},
}